### ISSUE TITLE
VirtualDub with FFV1

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/apex_video_kit_docs#1]
Keep an eye on [VirtualDub FFV1](http://www.av-rd.com/projects/2017-virtualdub_ffv1.html). It could become an alternative to `vrecord` for Windows.

**Comment by jfarbowitz** [comment]
Hi Reto!

Thanks for the suggestion. Will keep an eye out. Hope you're doing well.

Jonathan

**Comment by savcampbell** [comment]
I will note in the document that VirtualDub might be an option for Windows users in the future

**Comment by retokromer** [comment]
@savcampbell That’s fine!

**Comment by savcampbell** [comment]
Addressed in commit 57ad375fd92b838fbf43f1871277b815e2de91f9
