### ISSUE TITLE
RADD/PROUD/PRAVDA

### ISSUE THREAD

**Issue by ablwr** [amiaopensource/apex_video_kit_docs#9]
Would you consider linking to Dorothea Salo's work in your Additional Resources? It's very similar to the work being done here (small, portable digitization stations). https://radd.dsalo.info/

**Comment by privatezero** [comment]
Maybe this would be a good place to cross-link with the [amiaos open workflows doc](https://github.com/amiaopensource/open-workflows#resources)?

**Comment by ablwr** [comment]
Oh yeah, true, no need to reinvent the wheel, right?

**Comment by pvizner** [comment]
Absolutely! Couldn't agree more. Thanks!
